language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
true:
  branch: dev-app
notifications:
  slack:
    rooms:
      secure: L2/PV0HxDJa8ltDizLuoDkWq9z6JJ+uWxVVlaqeZk+iP7JuDQqQpRQ6ZJ2JdjRmWQUIlUSIM2ftgAXMVH9NP9IXMJYWRBe/4HK1+dqIA7XMmVaQmFFTyIHG+QAF9lWju58fGE30WxACJwvSgPKz3kpWyR3Phvuw0eiSfcgKy9jDQHo+eHe7CLNDNT0rjbtXqNdkTEd+q1rzTuqUP9b2ISNzA/WsMUfKnvePwrifCNrd1XJ5DdLtczUuduzaokEazSPayHXZuWPl+OYfS0MNYx9Pqt+ePJwUy0Eyw1CobipmDz7kwkuCS4ICXhDldUUuHfSobW7EZrG7sjgzbGhJq4zhKwobEP8EaZ4E9I6wPLQ1asG2MMDgaxhlNSj/E0OUwrKs7D/P/PqgRRtrqPEhdXEfy+gXDBnrKCGTQeNd8dAn73h+44TFfHZugdMvGwsV6zvfTK9gs8tNi58Ysg5Am1z2qKNRNVy4vMIqRuksbIArQmKbCeWwjrOTH3Pj76uvhP4PI/GPm6QkAsL5OnyiWd9BnQn5oa+shRE85tLGrmy+KlaiKgVpnC1B1qsLfHdO7KdTWex72zJMKn84NKUUeJ0u/bUqJ2N1ynFv3V5ILpRFDQXDSaKfq0v3NRpjedeQ1xorgjEucuQGEUm0RqiVBL1Vdz1wwjxyn9vf6eilZs7A=
    on_success: always
