language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
true:
  branch: dev-app
notifications:
  slack:
    rooms:
      secure: zQQkcCz6M6fHzwAF2/+fStdwjw6BYMwas1oSJWV4B6W6S4/3Vs6rGXogNI6LfoM6ktOUszvM/OaFf7DM33bUU6Gpq0baVOOuSHPVmDFvLki6IaAQ2YL2lHsQapjMJREgTf0tbp5uXVeqASnN3epsES98G6dN1mWHPxsedVaXleRNRWwyE2bJdTnR72herLbRK59mq/74B55dg+cGKJlxhzz7wdO+Vj3dzLgkxngnS+/qRhQkN5fGDPKfLtXlYTX/yUJHI0HD+Llb9mJLOqvSL21TZeI5OG55pF5ITK14Rsrv8yRCXiB0iCIukcLQMC6STut/5uTIAhVtajUkpuuRW1wBQckcBknrwMLVhT1Lvu/69A6iSyAPmUnPKFeTkoZ3Q5Oi15eBmb0y/dKsBbDnO6M4va+e/3Uz5dcjZv7oSRxohv9PrxTlSdL9tkU7/PyrhZktMg5YAd8wusr3eM1NxJysarcX9pswPMn2BO21kqvO8ZhEbfCR3uxcmn8ixV1VFA/p8FTz+doiyNki082Rntiqi1VZnqPRQI+o9LEq1ie02ypwDlcoPERIXf2608TLFnvGuDInoQnBHKbY38Cg4ehQcV48aVlH61w72qxXKYYsBITqc6MTlRqq78H8ey0Wa60Ti7dNn4PVUH68wrmvuCdZQhTY61LrKu+IZ4W37aE=
    on_success: always
