language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
true:
  branch: dev-app

addons:
  sonarcloud:
    organization: "Sonarcloud" 
    token:
      secure: "$SONAR_TOKEN" 
script:
  - sonar-scanner

notifications:
slack:
  rooms:
  - sytwull:GgiUiOJJeifKY0uamYUGF1Zr#e08