language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
true:
  branch: dev-app
notifications:
  slack:
    rooms:
      secure: Qrg/VyCbLCIuQ6HT2m9diSJByKGYk3BmHjSsqiWrct/8ex+IDUSIdO048dFfKKJHasgbji7tEr8MrfmNfUI2JKWIEub/NvssIdPDOM14+dN2se2zcAvC5kyy7bW8t26cZ3gIOhat9lV2jI/WE8RRTApIYqI1guUVLZGNJKcZ98ab1QYCGGwKDtlSAeK0AglR5ImKesPQf/zcpouTHA+/VOdmnWUcX9rrUNmpe2t36R04OmsWpC/5vAlU2mriwuu908Hl1T8WNwSvIM8oMQMLZniZFSmmcFVwEM1DRTgDSgpdEKGqzccjcXGX0bCu2/jpjWwVFEc0NAKul7kJa7ZQLTWBlDbVrooky7fn1lEe/sPhzuR/4XNBsruTAFrDeR+I47hUFNfiXCOXeVMy20C6tuiCI2eIJQjTCmzTWiYKezaFX9fvbYFkf89fbGxGSul6c/N1nFMJX9zbC+ADhIg6kPX+30CvzUCmhiaPY6OL+4Ioh7Tsw3cPWAgD389HBrAwkOcjO+/ogMOB1O4Ydun67C5hqMiovAt98TxoU7tMZ6ZvUg0edo5sA5XD02CNCf3Vm5AlTL3YJAElYW+JYyld553r7S1uciIp+duUXoQeY7priBTa1cg2wMrZoggkeJy4jyKU/lykAlCIZcdtZwjkLkr4iVMZJJYpzV/+m5nIT5o=
    on_success: always
