language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
true:
  branch: dev-app
notifications:
  slack:
    rooms:
      secure: pgMHs6xnf6Mit0B+cfTqZ7m8gmbVdX7e3XjtY1+BybFk94xLaXy4couqV0oMOK4Y18iXtLFrypR8EkTD9yMGJkIdSGdxQWTzm0AlAh1tKK3MksSrW04AkYqGw0SaYMpPqMgDNJvxcRCIgAEJHwKoIUvvt0somShni3wmNWbDqqG62FJ0+E+nakqH29Bs8VKDxLV0n+H1NiSot/bUK3jLggFkW5lVlubVHMTQ3xrmQvHEnRNVMgGrYURbed4+mXyWzlVNtPDpH8iYMDBD05OTI32egMwzrL4cAAuOAPXr19N3wjTviV33IMGxob23b23JrMr+L2wR4mAEcKU7Wb2JROpynpCORbgoKXYQy3dy3yf3CPUrKbrPTATI9xZryRdWxl5g5dI5F70B+yggXeusmNMoETXIn0ZwuRDtfzbhspQ12vFZB77FKZ4vPxhy/UaCDN9248P5D0zEZoBbXaPZTHGoqthgOqdCPRonCcposN4ogesAJl6fPUVvLGZ6ilq1bjSHCAz5LP0Dr4aOQQLOYVYqyQNUDf7VM+K0axPAjnv2Vu/Hz5w0vIQRGWMhQrLi3yAhVJoxHFk5lxYTsY+l+DX1sktddX2xRVShq/lhAAbxJYYJ237cjIdD3l67rieCkEu36rajuEiblhj44YgQX3vP57wH1CsPNohSPdccFg8=
    on_success: always
    