name: CI

on: [push]

jobs:
  coverage:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: cd ./backend && npm install
    - name: Generating Coverage information
      run: cd ./backend && npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}