name: Api Test

on: [push]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
      - run: cd ./backend && npm install

      - name: Run Test
        run: cd ./backend && npm run test